// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq18NVnXLITsNoOe11TbxDk7_IlpRC3pE',
    appId: '1:251341250349:web:be730eff6597062101fda4',
    messagingSenderId: '251341250349',
    projectId: 'my-mood-diary-asgmt',
    authDomain: 'my-mood-diary-asgmt.firebaseapp.com',
    storageBucket: 'my-mood-diary-asgmt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSB0oLKY9EVmhrmwwCZmhPDWX0Gw8XS20',
    appId: '1:251341250349:android:d548df6cf931d51c01fda4',
    messagingSenderId: '251341250349',
    projectId: 'my-mood-diary-asgmt',
    storageBucket: 'my-mood-diary-asgmt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0V8NzGWZxEpu1F9597IftUvlrAGq8-FI',
    appId: '1:251341250349:ios:432db7dc22cb634a01fda4',
    messagingSenderId: '251341250349',
    projectId: 'my-mood-diary-asgmt',
    storageBucket: 'my-mood-diary-asgmt.appspot.com',
    iosBundleId: 'com.example.tictokCloneAssignmentGraduation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq18NVnXLITsNoOe11TbxDk7_IlpRC3pE',
    appId: '1:251341250349:web:f67be6a0316deae901fda4',
    messagingSenderId: '251341250349',
    projectId: 'my-mood-diary-asgmt',
    authDomain: 'my-mood-diary-asgmt.firebaseapp.com',
    storageBucket: 'my-mood-diary-asgmt.appspot.com',
  );
}
